name: Assign PR Author as Assignee

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Check out action
        uses: actions/checkout@v3

      - name: Assign PR author
        uses: ./.github/actions/assign-pr-author
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
